import { Router } from "express";
import { authRouter } from "./modules/auth/auth.routes";
import { userRouter } from "./modules/users/user.routes";
import { loraRouter } from "./modules/lora/lora.routes";
import { loraNodeRouter } from "./modules/lora-nodes/lora-node.routes";
import { mapRouter } from "./modules/map/map.routes";
import { mobRouter } from "./modules/mobs/mob.routes";
import { mobMovementPlanRouter } from "./modules/mob-movement-plans/mob-movement-plan.routes";
import { mobPaddockAllocationRouter } from "./modules/mob-paddock-allocations/mob-paddock-allocation.routes";
import { paddockRouter } from "./modules/paddocks/paddock.routes";
import { cropSeasonRouter } from "./modules/crop-seasons/crop-season.routes";
import { paddockPlanRouter } from "./modules/paddock-plans/paddock-plan.routes";
import { productionPlanRouter } from "./modules/production-plans/production-plan.routes";
import { issueRouter } from "./modules/issues/issue.routes";
import { taskRouter } from "./modules/tasks/task.routes";
import { waterAssetRouter } from "./modules/water-assets/water-asset.routes";
import { waterLinkRouter } from "./modules/water-links/water-link.routes";
import { sensorRouter } from "./modules/sensors/sensor.routes";
import { sensorReadingRouter } from "./modules/sensor-readings/sensor-reading.routes";
import { feederRouter } from "./modules/feeders/feeder.routes";
import { hayLotRouter } from "./modules/hay-lots/hay-lot.routes";
import { grainLotRouter } from "./modules/grain-lots/grain-lot.routes";
import { feedEventRouter } from "./modules/feed-events/feed-event.routes";
import { contractorRouter } from "./modules/contractors/contractor.routes";
import { pestSpottingRouter } from "./modules/pest-spottings/pest-spotting.routes";
import { attachmentRouter } from "./modules/attachments/attachment.routes";
import { activityEventRouter } from "./modules/activity-events/activity-event.routes";
import { syncRouter } from "./modules/sync/sync.routes";
import { requireAuth } from "./shared/auth/auth.middleware";

export const apiRouter = Router();

apiRouter.get("/health", (_req, res) => {
  res.json({ ok: true, service: "croxton-east-api" });
});

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", requireAuth, userRouter);
apiRouter.use("/mobs", requireAuth, mobRouter);
apiRouter.use("/mob-paddock-allocations", requireAuth, mobPaddockAllocationRouter);
apiRouter.use("/mob-movement-plans", requireAuth, mobMovementPlanRouter);
apiRouter.use("/paddocks", requireAuth, paddockRouter);
apiRouter.use("/crop-seasons", requireAuth, cropSeasonRouter);
apiRouter.use("/paddock-plans", requireAuth, paddockPlanRouter);
apiRouter.use("/production-plans", requireAuth, productionPlanRouter);
apiRouter.use("/issues", requireAuth, issueRouter);
apiRouter.use("/tasks", requireAuth, taskRouter);
apiRouter.use("/feeders", requireAuth, feederRouter);
apiRouter.use("/hay-lots", requireAuth, hayLotRouter);
apiRouter.use("/grain-lots", requireAuth, grainLotRouter);
apiRouter.use("/feed-events", requireAuth, feedEventRouter);
apiRouter.use("/contractors", requireAuth, contractorRouter);
apiRouter.use("/pest-spottings", requireAuth, pestSpottingRouter);
apiRouter.use("/attachments", requireAuth, attachmentRouter);
apiRouter.use("/activity-events", requireAuth, activityEventRouter);
apiRouter.use("/lora-nodes", requireAuth, loraNodeRouter);
apiRouter.use("/sensors", requireAuth, sensorRouter);
apiRouter.use("/sensor-readings", requireAuth, sensorReadingRouter);
apiRouter.use("/water-assets", requireAuth, waterAssetRouter);
apiRouter.use("/water-links", requireAuth, waterLinkRouter);
apiRouter.use("/sync", requireAuth, syncRouter);
apiRouter.use("/map", requireAuth, mapRouter);
apiRouter.use("/lora", loraRouter);
